name: Orebfuscator
main: com.lishid.orebfuscator.Orebfuscator
version: 1.0
authors:
- lishid
- _Shevchik_
load: startup
description: >
             The most powerful and efficient Anti Xray
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> reload - Reload config
           /<command> status - Show plugin status